# Generated by Django 5.2.13 on 2026-04-23 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_choice',
            field=models.PositiveSmallIntegerField(choices=[(1, '🐶'), (2, '🐱'), (3, '🦊'), (4, '🐼'), (5, '🐨'), (6, '🐯'), (7, '🦁'), (8, '🐰')], default=1, help_text='Avatar predeterminado del usuario'),
        ),
    ]
