# Generated by Django 5.2.13 on 2026-04-23 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('barkposts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='barkpost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barkposts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='barkpost',
            index=models.Index(fields=['user', '-created_at'], name='barkposts_b_user_id_bb7a33_idx'),
        ),
    ]
