# Generated by Django 5.2.13 on 2026-04-23 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barkposts', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='barkpost',
            name='image',
            field=models.ImageField(blank=True, help_text='Imagen opcional adjunta al ladrido.', null=True, upload_to='barkposts/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='barkpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('barkpost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='barkposts.barkpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'barkposts_like',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'barkpost')},
            },
        ),
    ]
